name: custom_pin_screen
description: A flutter package to add screens with custom keyboards and pins to
  your mobile application.
version: 0.5.0
homepage: https://github.com/Mastersam07/custom_pin_screen

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter: 

  assets:
    - assets/fonts/

  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope/Manrope-Bold.ttf
        - asset: assets/fonts/Manrope/Manrope-ExtraBold.ttf
        - asset: assets/fonts/Manrope/Manrope-ExtraLight.ttf
        - asset: assets/fonts/Manrope/Manrope-Light.ttf
        - asset: assets/fonts/Manrope/Manrope-Medium.ttf
        - asset: assets/fonts/Manrope/Manrope-Regular.ttf
        - asset: assets/fonts/Manrope/Manrope-SemiBold.ttf
